[build]
target = "riscv64gc-unknown-none-elf"

# [target.riscv64gc-unknown-none-elf]
#linker = "riscv64-unknown-elf-gcc"
# rustflags = [
#"-C", "link-arg=-Tmpfs-platform/platform/platform_config_reference/linker/mpfs-ddr-loaded-by-boot-loader.ld",
#]
