[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
riscv = "0.12"
itoa = "1.0"

[build-dependencies]
cc = "1.0"
walkdir = "2.4"
